FROM scarv/libscarv.riscv-xcrypto:1.0.0 as builder
ARG DEBIAN_FRONTEND=noninteractive

ENV LOGO="\
Project \e[1;35mCLEO\e[0m by \e[0;34m\\\n\
   _____                .__    _______________  ___ \\\n\
  /  _  \_______   ____ |  |__ \_   _____/\   \/  / \\\n\
 /  /_\  \_  __ \_/ ___\|  |  \ |    __)   \     /  \\\n\
/    |    \  | \/\  \___|   Y  \|     \    /     \  \\\n\
\____|__  /__|    \___  >___|  /\___  /   /___/\  \ \\\n\
        \/            \/     \/     \/          \_/ \\\n\
\e[0m"

RUN echo "echo -e $LOGO" >> ~/.bashrc

RUN apt-get update && apt-get install -y \
        git wget libmpc-dev verilator pip

RUN pip install matplotlib numpy scipy tabulate scikit-learn pandas

ENTRYPOINT ["/bin/bash"]
